
image:
  file: .gitpod.Dockerfile

tasks:
  - name: install pre-commit hook
    init: |-
      pip install pre-commit
      pre-commit install
  - name: jekyll
    command: cd docs &&  bundle update && bundle exec jekyll serve --host=0.0.0.0 --drafts


ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - mhutchie.git-graph
    - yzhang.markdown-all-in-one
